Update Jenkinsfile_Promote

diff --git a/Jenkinsfile_Promote b/Jenkinsfile_Promote
--- a/Jenkinsfile_Promote
+++ b/Jenkinsfile_Promote
@@ -28,6 +28,17 @@ pipeline {
           container(name: 'awscli') {
             sh '''
             #!/bin/bash
+             # Check if COURSE or TEAM parameters are empty
+                if [ -z "$COURSE" ]; then
+                    echo "ERROR: COURSE parameter must be provided."
+                    exit 1
+                fi
+
+                if [ -z "$TEAM" ]; then
+                    echo "ERROR: TEAM parameter must be provided."
+                    exit 1
+                fi
+
             export AWS_DEFAULT_REGION=us-east-1
             API_build_num=$(aws ecr list-images --repository-name production-support-course  --filter "tagStatus=TAGGED" --query "imageIds[?contains(imageTag, '${TEAM}api')].imageTag" --output text | sed "s/\\t/\\n/g" | sed "s/-/ /g" | sort -k3,3n | tail -1 | awk '{print $3}')
             echo $API_build_num
