changed script back to original 3 commands

diff --git a/Jenkinsfile_Test b/Jenkinsfile_Test
--- a/Jenkinsfile_Test
+++ b/Jenkinsfile_Test
@@ -17,14 +17,12 @@ pipeline {
 	stage('Search Most Recent Image Version') {
 	    steps{
 	        script{
-	            sh """
+		    sh """
 		    curl "http://ecrlist-ps.computerlab.online/index.php" | grep -Eo "(${COHORT}${TEAM}(fe|db|api)-dev-[0-9]*)" > image_list.txt
 		    sort -nro image_list.txt image_list.txt
-		    echo "latest image version: "
 		    grep fe -m1 image_list.txt || { echo 'fe image not found';exit 1; }
-		    echo "latest image version: "
 		    grep db -m1 image_list.txt || { echo 'db image not found';exit 1; }
-		    echo "Latest Version: " $(grep api -m1 image_list.txt || { echo 'api image not found'; exit 1; })
+		    grep api -m1 image_list.txt || { echo 'api image not found';exit 1; }
 	            """
 	      	}
 	    }
