Update pipeline_promote_multi_team

diff --git a/utils/pipeline_promote_multi_team b/utils/pipeline_promote_multi_team
--- a/utils/pipeline_promote_multi_team
+++ b/utils/pipeline_promote_multi_team
@@ -30,16 +30,65 @@ pipeline {
             TEAM="team$(printf "%02d" ${i})"
             API_image=$(aws ecr list-images --repository-name production-support-course | grep "${COURSE}${TEAM}api-dev-" | sort -V | tail -1 | awk -F':' '{print$2}' | tr -d '"')
             echo $API_image
-            API_build_num=$(echo $API_image | awk -F'-' '{print$3})
+            API_build_num=$(echo $API_image | awk -F'-' '{print$3}')
             DB_image=$(aws ecr list-images --repository-name production-support-course | grep "${COURSE}${TEAM}db-dev-" | sort -V | tail -1 | awk -F':' '{print$2}' | tr -d '"')
             echo $API_build_num
-            DB_build_num=$(echo $DB_image | awk -F'-' '{print$3})
+            DB_build_num=$(echo $DB_image | awk -F'-' '{print$3}')
             FE_image=$(aws ecr list-images --repository-name production-support-course | grep "${COURSE}${TEAM}fe-dev-" | sort -V | tail -1 | awk -F':' '{print$2}' | tr -d '"')
-            FE_build_num=$(echo $FE_image | awk -F'-' '{print$3})
+            FE_build_num=$(echo $FE_image | awk -F'-' '{print$3}')
             APIMANIFEST=$(aws ecr batch-get-image --repository-name production-support-course --image-ids imageTag=${COURSE}${TEAM}api-dev-${API_build_num} --query 'images[].imageManifest' --output text)
             DBMANIFEST=$(aws ecr batch-get-image --repository-name production-support-course --image-ids imageTag=${COURSE}${TEAM}db-dev-${DB_build_num} --query 'images[].imageManifest' --output text)
             FEMANIFEST=$(aws ecr batch-get-image --repository-name production-support-course --image-ids imageTag=${COURSE}${TEAM}fe-dev-${FE_build_num} --query 'images[].imageManifest' --output text)
-            done'''
+
+            # Check API
+            if [ $(aws ecr describe-images --repository-name production-support-course | grep "${COURSE}${TEAM}api-prod-${API_build_num}" | wc -l) -eq 0 ]
+            then
+              # We don't have prod so tag Dev to prod
+              if ! aws ecr put-image --repository-name production-support-course --image-tag "${COURSE}${TEAM}api-prod-${API_build_num}" --image-manifest "$APIMANIFEST"
+              then
+                exitvalue=1
+              fi
+            fi
+            # Check DB
+            if [ $(aws ecr describe-images --repository-name production-support-course | grep "${COURSE}${TEAM}db-prod-${DB_build_num}" | wc -l) -eq 0 ]
+            then
+              # We don't have uat so tag Dev to prod
+              if ! aws ecr put-image --repository-name production-support-course --image-tag "${COURSE}${TEAM}db-prod-${DB_build_num}" --image-manifest "$DBMANIFEST"
+              then
+                exitvalue="2"
+              fi
+            fi
+            
+            # Check Front End
+            if [ $(aws ecr describe-images --repository-name production-support-course | grep "${COURSE}${TEAM}fe-prod-${FE_build_num}" | wc -l) -eq 0 ]
+            then
+              # We don't have uat so tag Dev to prod
+              if ! aws ecr put-image --repository-name production-support-course --image-tag "${COURSE}${TEAM}fe-prod-${FE_build_num}" --image-manifest "$FEMANIFEST"
+              then
+                exitvalue=3
+              fi
+            fi
+
+          case ${exitvalue} in
+            0) echo "Update OK"
+               ;;
+            1) echo "API failed to push to repository"
+               ;;
+            2) echo "DB failed to push to repository"
+               ;;
+            3) echo "AC failed to push to repository"
+               ;;
+            12) echo "API and DB failed to push to repository"
+               ;;
+            13) echo "API and AC failed to push to repository"
+               ;;
+            23) echo "DB and AC failed to push to repository"
+               ;;
+            123) echo "All images failed to push to repository"
+               ;;
+          esac
+          exit ${exitvalue}
+          done'''
         }
       }
     }
